---
services:
  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.file.directory=/etc/traefik/certs"
      - "--providers.file.watch=true"
      - "--serversTransport.insecureSkipVerify=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/certs:/etc/traefik/certs
    environment:
      - "TZ=${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.traefik-docker.loadbalancer.server.port=8080"
    restart: unless-stopped

  gitlab:
    image: 'gitlab/gitlab-ce:${VERSION}'
    container_name: 'gitlab'
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_DOMAIN}'
        registry_external_url 'https://${REGISTRY_DOMAIN}'
        gitlab_rails['gitlab_email_enabled'] = 'false'
        gitlab_rails['gitlab_shell_ssh_port'] = '22'
        gitlab_rails['time_zone'] = 'America/Argentina/Buenos_Aires'
        gitlab_rails['gitlab_username_changing_enabled'] = 'false'
        #gitlab_rails['gitlab_default_projects_features_issues'] = 'true'
        #gitlab_rails['gitlab_default_projects_features_merge_requests'] = 'true'
        #gitlab_rails['gitlab_default_projects_features_wiki'] = 'true'
        #gitlab_rails['gitlab_default_projects_features_snippets'] = 'true'
        #gitlab_rails['gitlab_default_projects_features_builds'] = 'true'
        #gitlab_rails['gitlab_default_projects_features_container_registry'] = 'true'
        gitlab_pages['enable'] = true
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    ports:
      - '22:22'
    expose:
      - '22'
      - '80'
      - '443'
      - '5005'
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${GITLAB_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.routers.registry.rule=Host(`${REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.services.registry.loadbalancer.server.port=5005"
      - "traefik.http.routers.registry.service=registry"
    restart: unless-stopped

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    extra_hosts:
      - "${GITLAB_DOMAIN}:${GITLAB_IP}"
      - "${REGISTRY_DOMAIN}:${GITLAB_IP}"
    environment:
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        set -e
        if [ ! -s /etc/gitlab-runner/config.toml ]; then
          echo ">>> Registering runner..."
          gitlab-runner register \
            --non-interactive \
            --url "https://${GITLAB_DOMAIN}" \
            --token "$${RUNNER_TOKEN}" \
            --executor docker \
            --docker-image ${RUNNER_DOCKER_IMAGE} \
            --docker-privileged \
            --docker-volumes /certs/client \
            --docker-volumes /cache \
            --tls-ca-file /etc/gitlab-runner/certs/${GITLAB_DOMAIN}.crt \
            --description docker-privileged-runner
        fi
        exec gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent2
    ports:
      - "10050:10050"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ZBX_SERVER_HOST=${ZABBIX_SERVER}
      - ZBX_HOSTNAME=ct-gitlab
    extra_hosts:
      - "zabbix.lan:${ZABBIX_SERVER}"
